import type { QuizRound } from '@/types/name-page'

export const QUIZ_DATA: Record<string, QuizRound[]> = {
  male: [
    {
      round: 1,
      question_en: 'If your name had a personality, what would it be?',
      question_zh: '如果你的名字有一种性格，会是什么样的？',
      options: [
        {
          emoji: '🦁',
          label_en: 'Bold & Fearless',
          label_zh: '勇敢无畏',
          desc_en: 'A name that commands respect and strength',
          desc_zh: '令人敬畏的强势之名',
          filters: [{ field: 'vibe', op: 'any_of', value: ['strong', 'fierce', 'brave'] }],
        },
        {
          emoji: '🧊',
          label_en: 'Cool & Composed',
          label_zh: '冷静沉着',
          desc_en: 'Calm confidence with an edge',
          desc_zh: '从容不迫中带着锋芒',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cool', 'edgy', 'calm'] }],
        },
        {
          emoji: '🌸',
          label_en: 'Kind & Warm-hearted',
          label_zh: '温柔善良',
          desc_en: 'Gentle warmth that puts people at ease',
          desc_zh: '如春风般温暖人心',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'kind'] }],
        },
        {
          emoji: '👑',
          label_en: 'Refined & Noble',
          label_zh: '高雅尊贵',
          desc_en: 'Sophistication and timeless class',
          desc_zh: '优雅从容的贵族气质',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'noble', 'graceful'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Deep & Enigmatic',
          label_zh: '深沉神秘',
          desc_en: 'Mystique that draws people in',
          desc_zh: '引人深入的神秘魅力',
          filters: [{ field: 'vibe', op: 'any_of', value: ['mysterious', 'dark', 'deep'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the scene that speaks to your soul',
      question_zh: '选一个最能触动你内心的场景',
      options: [
        {
          emoji: '🌋',
          label_en: 'A volcano erupting at dawn',
          label_zh: '黎明时分喷发的火山',
          desc_en: 'Unstoppable power and energy',
          desc_zh: '势不可挡的力量与能量',
          filters: [{ field: 'element', op: 'any_of', value: ['fire', 'thunder', 'sun'] }],
        },
        {
          emoji: '🌊',
          label_en: 'Waves crashing on moonlit cliffs',
          label_zh: '月光下拍打悬崖的海浪',
          desc_en: 'Deep currents beneath the surface',
          desc_zh: '平静之下暗流涌动',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'moon', 'ice'] }],
        },
        {
          emoji: '🏔️',
          label_en: 'Snow-capped peaks at sunrise',
          label_zh: '日出时分的雪山之巅',
          desc_en: 'Immovable strength, towering above all',
          desc_zh: '巍然屹立，俯瞰万物',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'earth', 'light'] }],
        },
        {
          emoji: '🌾',
          label_en: 'Wind sweeping through ancient fields',
          label_zh: '微风拂过古老的田野',
          desc_en: 'Freedom, openness, and roots',
          desc_zh: '自由、辽阔与根脉',
          filters: [{ field: 'element', op: 'any_of', value: ['wind', 'earth', 'sky'] }],
        },
        {
          emoji: '🌌',
          label_en: 'Stars reflected in a still lake',
          label_zh: '星辰倒映在静谧的湖面',
          desc_en: 'Infinite depth and wonder',
          desc_zh: '无尽的深邃与奇妙',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'moon', 'dark'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How should your name feel when spoken aloud?',
      question_zh: '当你的名字被念出来时，应该给人什么感觉？',
      options: [
        {
          emoji: '⚔️',
          label_en: 'Like an ancient warrior\'s war cry',
          label_zh: '如同古代武士的战吼',
          desc_en: 'Timeless, powerful, legendary',
          desc_zh: '古老、强悍、传奇',
          filters: [{ field: 'era', op: 'any_of', value: ['ancient', 'traditional'] }],
        },
        {
          emoji: '🎌',
          label_en: 'Like a character from a classic novel',
          label_zh: '像经典小说里走出的人物',
          desc_en: 'Familiar, trusted, deeply rooted',
          desc_zh: '耳熟能详、值得信赖',
          filters: [{ field: 'era', op: 'eq', value: 'traditional' }],
        },
        {
          emoji: '🎧',
          label_en: 'Like a chart-topping song',
          label_zh: '像一首风靡的流行歌曲',
          desc_en: 'Fresh, current, full of energy',
          desc_zh: '新鲜、当代、充满活力',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'I like surprises — any era is fine',
          label_zh: '我喜欢惊喜——任何时代都行',
          desc_en: 'Let fate decide the era',
          desc_zh: '让命运来决定',
          filters: [],
        },
      ],
    },
  ],
}
