import type { QuizRound } from '@/types/name-page'

export const QUIZ_DATA: Record<string, QuizRound[]> = {
  female: [
    {
      round: 1,
      question_en: 'What kind of aura should your name carry?',
      question_zh: '你希望这个名字带着怎样的气场？',
      options: [
        {
          emoji: '🌷',
          label_en: 'Graceful & Refined',
          label_zh: '优雅娴静',
          desc_en: 'A name with polished beauty and timeless poise',
          desc_zh: '带着细腻美感与从容气质的名字',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'serene', 'noble'] }],
        },
        {
          emoji: '🎀',
          label_en: 'Sweet & Adorable',
          label_zh: '甜美可爱',
          desc_en: 'Soft, lovable, and effortlessly charming',
          desc_zh: '轻盈讨喜，让人一听就有好感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cute', 'playful', 'gentle'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Mystical & Dreamy',
          label_zh: '朦胧梦幻',
          desc_en: 'A name wrapped in moonlight, wonder, and intrigue',
          desc_zh: '像月色般朦胧，带着一点神秘感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['mysterious', 'serene', 'dark'] }],
        },
        {
          emoji: '🌿',
          label_en: 'Warm & Gentle',
          label_zh: '温柔治愈',
          desc_en: 'Comforting, kind, and naturally graceful',
          desc_zh: '像春风一样柔和，让人安心',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'elegant'] }],
        },
        {
          emoji: '⚡',
          label_en: 'Bright & Strong',
          label_zh: '明亮坚定',
          desc_en: 'Elegant femininity with inner strength',
          desc_zh: '既有女性气质，也有清晰锋芒',
          filters: [{ field: 'vibe', op: 'any_of', value: ['strong', 'cool', 'noble'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Choose the scene your name belongs to',
      question_zh: '选一个最像你名字所属世界的场景',
      options: [
        {
          emoji: '🌸',
          label_en: 'Cherry blossoms drifting over a shrine path',
          label_zh: '神社参道上飘落的樱花',
          desc_en: 'Delicate, romantic, and classically Japanese',
          desc_zh: '柔美、浪漫，也很有日式风情',
          filters: [{ field: 'element', op: 'any_of', value: ['flower', 'wind', 'light'] }],
        },
        {
          emoji: '🌊',
          label_en: 'An ocean glowing at sunrise',
          label_zh: '晨光里发亮的海面',
          desc_en: 'Fresh energy, openness, and luminous calm',
          desc_zh: '清新开阔，带着发光的宁静感',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'sun', 'light'] }],
        },
        {
          emoji: '🌕',
          label_en: 'A moonlit garden after the rain',
          label_zh: '雨后月色笼罩的庭园',
          desc_en: 'Quiet beauty with a touch of mystery',
          desc_zh: '安静漂亮，又有一点神秘',
          filters: [{ field: 'element', op: 'any_of', value: ['moon', 'water', 'flower'] }],
        },
        {
          emoji: '❄️',
          label_en: 'Snow settling on a mountain temple',
          label_zh: '白雪落在山寺之间',
          desc_en: 'Still, pure, and dignified',
          desc_zh: '清冷、纯净，带着端庄感',
          filters: [{ field: 'element', op: 'any_of', value: ['ice', 'mountain', 'earth'] }],
        },
        {
          emoji: '✨',
          label_en: 'A sky full of stars just before dawn',
          label_zh: '天将亮时满天闪烁的星光',
          desc_en: 'Hopeful, magical, and full of possibility',
          desc_zh: '梦幻又有希望感，像新故事开场',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'sky', 'light'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'When someone says your name, how should it sound?',
      question_zh: '当别人念出这个名字时，你希望它听起来像什么？',
      options: [
        {
          emoji: '📜',
          label_en: 'Like a line from a classical poem',
          label_zh: '像古典和歌里的一句诗',
          desc_en: 'Elegant, literary, and timeless',
          desc_zh: '文雅、古典、经久不衰',
          filters: [{ field: 'era', op: 'any_of', value: ['ancient', 'traditional'] }],
        },
        {
          emoji: '🎐',
          label_en: 'Like a soft summer bell in the breeze',
          label_zh: '像风里轻响的夏日风铃',
          desc_en: 'Light, airy, and soothing',
          desc_zh: '轻盈柔和，让人听了很舒服',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s'] }],
        },
        {
          emoji: '🎶',
          label_en: 'Like a modern melody everyone remembers',
          label_zh: '像一段让人记住的现代旋律',
          desc_en: 'Fresh, bright, and effortlessly memorable',
          desc_zh: '新鲜明亮，听过就容易记住',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Surprise me — any style can work',
          label_zh: '给我惊喜吧——什么风格都可以',
          desc_en: 'Let the perfect name find you',
          desc_zh: '让最适合你的名字自己出现',
          filters: [],
        },
      ],
    },
  ],
  male: [
    {
      round: 1,
      question_en: 'If your name had a personality, what would it be?',
      question_zh: '如果你的名字有一种性格，会是什么样的？',
      options: [
        {
          emoji: '🦁',
          label_en: 'Bold & Fearless',
          label_zh: '勇敢无畏',
          desc_en: 'A name that commands respect and strength',
          desc_zh: '令人敬畏的强势之名',
          filters: [{ field: 'vibe', op: 'any_of', value: ['strong', 'fierce', 'brave'] }],
        },
        {
          emoji: '🧊',
          label_en: 'Cool & Composed',
          label_zh: '冷静沉着',
          desc_en: 'Calm confidence with an edge',
          desc_zh: '从容不迫中带着锋芒',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cool', 'edgy', 'calm'] }],
        },
        {
          emoji: '🌸',
          label_en: 'Kind & Warm-hearted',
          label_zh: '温柔善良',
          desc_en: 'Gentle warmth that puts people at ease',
          desc_zh: '如春风般温暖人心',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'kind'] }],
        },
        {
          emoji: '👑',
          label_en: 'Refined & Noble',
          label_zh: '高雅尊贵',
          desc_en: 'Sophistication and timeless class',
          desc_zh: '优雅从容的贵族气质',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'noble', 'graceful'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Deep & Enigmatic',
          label_zh: '深沉神秘',
          desc_en: 'Mystique that draws people in',
          desc_zh: '引人深入的神秘魅力',
          filters: [{ field: 'vibe', op: 'any_of', value: ['mysterious', 'dark', 'deep'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the scene that speaks to your soul',
      question_zh: '选一个最能触动你内心的场景',
      options: [
        {
          emoji: '🌋',
          label_en: 'A volcano erupting at dawn',
          label_zh: '黎明时分喷发的火山',
          desc_en: 'Unstoppable power and energy',
          desc_zh: '势不可挡的力量与能量',
          filters: [{ field: 'element', op: 'any_of', value: ['fire', 'thunder', 'sun'] }],
        },
        {
          emoji: '🌊',
          label_en: 'Waves crashing on moonlit cliffs',
          label_zh: '月光下拍打悬崖的海浪',
          desc_en: 'Deep currents beneath the surface',
          desc_zh: '平静之下暗流涌动',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'moon', 'ice'] }],
        },
        {
          emoji: '🏔️',
          label_en: 'Snow-capped peaks at sunrise',
          label_zh: '日出时分的雪山之巅',
          desc_en: 'Immovable strength, towering above all',
          desc_zh: '巍然屹立，俯瞰万物',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'earth', 'light'] }],
        },
        {
          emoji: '🌾',
          label_en: 'Wind sweeping through ancient fields',
          label_zh: '微风拂过古老的田野',
          desc_en: 'Freedom, openness, and roots',
          desc_zh: '自由、辽阔与根脉',
          filters: [{ field: 'element', op: 'any_of', value: ['wind', 'earth', 'sky'] }],
        },
        {
          emoji: '🌌',
          label_en: 'Stars reflected in a still lake',
          label_zh: '星辰倒映在静谧的湖面',
          desc_en: 'Infinite depth and wonder',
          desc_zh: '无尽的深邃与奇妙',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'moon', 'dark'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How should your name feel when spoken aloud?',
      question_zh: '当你的名字被念出来时，应该给人什么感觉？',
      options: [
        {
          emoji: '⚔️',
          label_en: 'Like an ancient warrior\'s war cry',
          label_zh: '如同古代武士的战吼',
          desc_en: 'Timeless, powerful, legendary',
          desc_zh: '古老、强悍、传奇',
          filters: [{ field: 'era', op: 'any_of', value: ['ancient', 'traditional'] }],
        },
        {
          emoji: '🎌',
          label_en: 'Like a character from a classic novel',
          label_zh: '像经典小说里走出的人物',
          desc_en: 'Familiar, trusted, deeply rooted',
          desc_zh: '耳熟能详、值得信赖',
          filters: [{ field: 'era', op: 'eq', value: 'traditional' }],
        },
        {
          emoji: '🎧',
          label_en: 'Like a chart-topping song',
          label_zh: '像一首风靡的流行歌曲',
          desc_en: 'Fresh, current, full of energy',
          desc_zh: '新鲜、当代、充满活力',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'I like surprises — any era is fine',
          label_zh: '我喜欢惊喜——任何时代都行',
          desc_en: 'Let fate decide the era',
          desc_zh: '让命运来决定',
          filters: [],
        },
      ],
    },
  ],
  'last-names': [
    {
      round: 1,
      question_en: 'What kind of surname presence do you want first?',
      question_zh: '你希望这个姓氏先给人什么第一印象？',
      options: [
        {
          emoji: '🏯',
          label_en: 'Traditional & Distinguished',
          label_zh: '传统端正',
          desc_en: 'A surname that feels rooted, formal, and recognizably Japanese',
          desc_zh: '有根基、有分量，一看就很日式的姓氏感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['noble', 'elegant', 'serene'] }],
        },
        {
          emoji: '🌿',
          label_en: 'Natural & Peaceful',
          label_zh: '自然静雅',
          desc_en: 'Landscape-driven surnames with soft, grounded imagery',
          desc_zh: '带着山川田野感，温和又有画面',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'water', 'earth', 'wind'] }],
        },
        {
          emoji: '🗡️',
          label_en: 'Sharp & Memorable',
          label_zh: '利落有记忆点',
          desc_en: 'Surnames with a cooler edge and stronger silhouette',
          desc_zh: '更干净利落，也更容易留下印象',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cool', 'strong', 'edgy'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Show me a broad mix',
          label_zh: '先给我看更广一点的混合风格',
          desc_en: 'Let the surname patterns reveal themselves naturally',
          desc_zh: '先广泛看看，再从中挑出偏好',
          filters: [],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Which image feels most like the surname world you want?',
      question_zh: '哪个画面最像你想要的姓氏世界观？',
      options: [
        {
          emoji: '⛰️',
          label_en: 'Mountain ridges and forest paths',
          label_zh: '山岭与林间小路',
          desc_en: 'Grounded, enduring, and deeply tied to place',
          desc_zh: '沉稳持久，和土地、地形紧紧相连',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'earth', 'wind'] }],
        },
        {
          emoji: '🌊',
          label_en: 'Rivers, coasts, and moving water',
          label_zh: '河流、海岸与流动的水',
          desc_en: 'Fluid, clear, and easy to pair with many given names',
          desc_zh: '流动感强，也更容易和很多名字搭配',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'wind', 'light'] }],
        },
        {
          emoji: '🌾',
          label_en: 'Fields, villages, and open plains',
          label_zh: '田野、村落与开阔原野',
          desc_en: 'Familiar, lived-in, and classically surname-like',
          desc_zh: '生活感很强，也很像真实存在的日本姓氏',
          filters: [{ field: 'element', op: 'any_of', value: ['earth', 'light', 'wind'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Quiet moonlight and shadow',
          label_zh: '安静月色与一点幽深感',
          desc_en: 'Refined, restrained, and slightly enigmatic',
          desc_zh: '内敛克制，带一点神秘与高级感',
          filters: [{ field: 'element', op: 'any_of', value: ['moon', 'dark', 'water'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'When paired with a given name, how should the surname land?',
      question_zh: '当它和名字连在一起时，你希望这个姓氏落下什么感觉？',
      options: [
        {
          emoji: '📜',
          label_en: 'Timeless and literary',
          label_zh: '古典耐看',
          desc_en: 'A surname that could belong in history, fiction, or family records',
          desc_zh: '像会出现在家谱、小说和旧时代里的姓氏',
          filters: [{ field: 'era', op: 'any_of', value: ['ancient', 'traditional'] }],
        },
        {
          emoji: '✨',
          label_en: 'Clean and modern',
          label_zh: '干净现代',
          desc_en: 'Still Japanese in feeling, but lighter and more current',
          desc_zh: '仍然很日式，但更轻、更当代、更利落',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Either can work — surprise me',
          label_zh: '经典现代都行——给我惊喜',
          desc_en: 'Let the strongest full-name rhythm win',
          desc_zh: '让整体全名的节奏来决定',
          filters: [],
        },
      ],
    },
  ],
  boy: [
    {
      round: 1,
      question_en: 'What kind of boy-name energy are you after?',
      question_zh: '你更想要哪种男孩名字气质？',
      options: [
        {
          emoji: '☀️',
          label_en: 'Bright & Cheerful',
          label_zh: '明亮开朗',
          desc_en: 'Friendly, sunny, and easy to love',
          desc_zh: '阳光、亲切、让人一听就有好感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['bright', 'warm', 'gentle'] }],
        },
        {
          emoji: '🛡️',
          label_en: 'Strong & Dependable',
          label_zh: '可靠稳重',
          desc_en: 'Solid names with protective, grounded energy',
          desc_zh: '踏实稳当，带着守护感的名字',
          filters: [{ field: 'vibe', op: 'any_of', value: ['strong', 'brave', 'calm'] }],
        },
        {
          emoji: '🌿',
          label_en: 'Gentle & Thoughtful',
          label_zh: '温柔细腻',
          desc_en: 'Soft-spoken names with kindness at the core',
          desc_zh: '温和耐听，核心是体贴与善意',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'kind', 'serene'] }],
        },
        {
          emoji: '⚡',
          label_en: 'Cool & Energetic',
          label_zh: '利落有活力',
          desc_en: 'Sharp, modern names with momentum',
          desc_zh: '现代利落，带着行动力和少年感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cool', 'edgy', 'bright'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the image that fits your ideal name',
      question_zh: '选一个最像你理想名字的画面',
      options: [
        {
          emoji: '🌊',
          label_en: 'Morning light over the sea',
          label_zh: '海面上的清晨微光',
          desc_en: 'Fresh, open, and full of possibility',
          desc_zh: '清新开阔，带着成长感',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'sun', 'sky'] }],
        },
        {
          emoji: '⛰️',
          label_en: 'A trail through mountain air',
          label_zh: '山风穿过林间小径',
          desc_en: 'Steady, natural, and quietly strong',
          desc_zh: '自然沉稳，不张扬但很有力量',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'earth', 'wind'] }],
        },
        {
          emoji: '🔥',
          label_en: 'A spark that becomes a fire',
          label_zh: '一点火星慢慢燃成火焰',
          desc_en: 'Driven, brave, and hard to ignore',
          desc_zh: '有冲劲、有胆量，也很有存在感',
          filters: [{ field: 'element', op: 'any_of', value: ['fire', 'thunder', 'light'] }],
        },
        {
          emoji: '🌙',
          label_en: 'A quiet night with a clear moon',
          label_zh: '安静夜色里的一轮明月',
          desc_en: 'Calm, thoughtful, and a little poetic',
          desc_zh: '安静克制，带一点诗意和思考感',
          filters: [{ field: 'element', op: 'any_of', value: ['moon', 'water', 'light'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How should the name sound when someone says it?',
      question_zh: '当别人念出这个名字时，你希望它听起来怎样？',
      options: [
        {
          emoji: '🏮',
          label_en: 'Classic and timeless',
          label_zh: '经典耐听',
          desc_en: 'Names that feel rooted and enduring',
          desc_zh: '有传统质感，放久了也不过时',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎧',
          label_en: 'Modern and lively',
          label_zh: '现代有活力',
          desc_en: 'Current, memorable, and easy to say',
          desc_zh: '新鲜好记，念起来很顺口',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'I want a mix — surprise me',
          label_zh: '我想混搭一点——给我惊喜',
          desc_en: 'Let the full-name vibe lead the way',
          desc_zh: '让整体感觉自己选中我',
          filters: [],
        },
      ],
    },
  ],
  girl: [
    {
      round: 1,
      question_en: 'What kind of girl-name feeling do you want first?',
      question_zh: '你最先想要哪种女孩名字感觉？',
      options: [
        {
          emoji: '🌸',
          label_en: 'Pretty & Soft',
          label_zh: '柔美好看',
          desc_en: 'A name that feels delicate, sweet, and easy to adore',
          desc_zh: '听起来柔软、漂亮、让人自然喜欢的名字',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cute', 'gentle', 'elegant'] }],
        },
        {
          emoji: '✨',
          label_en: 'Bright & Lively',
          label_zh: '明亮灵动',
          desc_en: 'Fresh energy, sparkle, and a cheerful impression',
          desc_zh: '轻快有神采，带着一点闪亮感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['warm', 'playful', 'bright'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Dreamy & Poetic',
          label_zh: '梦幻诗意',
          desc_en: 'A name with quiet beauty and a little mystery',
          desc_zh: '安静好看，带一点朦胧和故事感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['mysterious', 'serene', 'elegant'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Show me a broad mix',
          label_zh: '先给我更广一点的混合风格',
          desc_en: 'Let me compare several girl-name directions first',
          desc_zh: '先多看几种路线，再决定偏好',
          filters: [],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the image that suits your ideal name',
      question_zh: '选一个最像你理想名字的画面',
      options: [
        {
          emoji: '🌷',
          label_en: 'A flower garden after the rain',
          label_zh: '雨后盛开的花园',
          desc_en: 'Fresh, floral, and naturally expressive',
          desc_zh: '清新、有花感，也很有生命力',
          filters: [{ field: 'element', op: 'any_of', value: ['flower', 'light', 'water'] }],
        },
        {
          emoji: '🌊',
          label_en: 'Morning light on the sea',
          label_zh: '海面上的晨光',
          desc_en: 'Open, bright, and full of possibility',
          desc_zh: '开阔明亮，像新的一天刚开始',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'sun', 'light'] }],
        },
        {
          emoji: '🌌',
          label_en: 'Stars above a quiet night sky',
          label_zh: '夜空里安静发亮的星',
          desc_en: 'Dreamy, lyrical, and a little magical',
          desc_zh: '梦幻、轻盈，也带一点奇妙感',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'sky', 'moon'] }],
        },
        {
          emoji: '🍃',
          label_en: 'A breeze through leaves and sunlight',
          label_zh: '树叶间穿过的微风与日光',
          desc_en: 'Gentle, natural, and easy on the ear',
          desc_zh: '自然柔和，念起来也会很舒服',
          filters: [{ field: 'element', op: 'any_of', value: ['wind', 'light', 'earth'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How should the name sound when spoken?',
      question_zh: '当别人念出这个名字时，你希望它听起来怎样？',
      options: [
        {
          emoji: '📜',
          label_en: 'Classic and graceful',
          label_zh: '古典优雅',
          desc_en: 'A name with timeless softness and literary charm',
          desc_zh: '有经典感，也有一点文雅余韵',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎀',
          label_en: 'Cute and instantly lovable',
          label_zh: '可爱又讨喜',
          desc_en: 'Light, sweet, and easy to remember',
          desc_zh: '轻盈甜美，听过就容易有好感',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Any era is fine — surprise me',
          label_zh: '什么时代都可以——给我惊喜',
          desc_en: 'Let the overall full-name feeling decide',
          desc_zh: '让整体全名气质自己胜出',
          filters: [],
        },
      ],
    },
  ],
  'last-names-common': [
    {
      round: 1,
      question_en: 'What should a common Japanese surname feel like?',
      question_zh: '你希望常见日本姓氏给人的第一感觉是什么？',
      options: [
        {
          emoji: '🏡',
          label_en: 'Familiar and everyday',
          label_zh: '熟悉日常',
          desc_en: 'A surname that feels believable, grounded, and widely used',
          desc_zh: '真实常见、很有生活感，也容易让人接受',
          filters: [{ field: 'popularity', op: 'any_of', value: ['very_common', 'common'] }],
        },
        {
          emoji: '🌿',
          label_en: 'Natural and landscape-rooted',
          label_zh: '自然地景感',
          desc_en: 'Common surnames shaped by rivers, fields, mountains, and villages',
          desc_zh: '来自山川田野与聚落意象的常见姓氏',
          filters: [{ field: 'element', op: 'any_of', value: ['earth', 'water', 'mountain', 'wind'] }],
        },
        {
          emoji: '✨',
          label_en: 'Clean and easy to pair',
          label_zh: '干净顺口，容易搭配',
          desc_en: 'Popular surnames that work smoothly with many given names',
          desc_zh: '和很多名字都好搭，整体念起来很自然',
          filters: [{ field: 'vibe', op: 'any_of', value: ['serene', 'elegant', 'noble'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Which scene matches your preferred surname style?',
      question_zh: '哪个场景最像你想要的常见姓氏风格？',
      options: [
        {
          emoji: '🌾',
          label_en: 'Rice fields and open plains',
          label_zh: '稻田与开阔平原',
          desc_en: 'Warm, familiar, and rooted in everyday Japan',
          desc_zh: '温和熟悉，很像现实生活里的日本姓氏',
          filters: [{ field: 'element', op: 'any_of', value: ['earth', 'light', 'wind'] }],
        },
        {
          emoji: '🌊',
          label_en: 'Rivers and flowing water',
          label_zh: '河流与流动的水',
          desc_en: 'Clear, smooth, and easy to combine into full names',
          desc_zh: '清楚顺滑，也很适合做全名搭配',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'wind', 'light'] }],
        },
        {
          emoji: '⛰️',
          label_en: 'Mountain paths and old roads',
          label_zh: '山路与旧道',
          desc_en: 'Steady, traditional, and quietly enduring',
          desc_zh: '沉稳耐看，有一点传统根脉感',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'earth', 'wind'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'When paired with a given name, how should it land?',
      question_zh: '当它和名字配在一起时，你希望这个常见姓氏呈现什么感觉？',
      options: [
        {
          emoji: '🪶',
          label_en: 'Soft and natural',
          label_zh: '自然轻松',
          desc_en: 'The full name should sound effortless and lived-in',
          desc_zh: '整体全名要像真实会被使用的名字一样自然',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'modern'] }],
        },
        {
          emoji: '🏮',
          label_en: 'Traditional and dependable',
          label_zh: '传统可靠',
          desc_en: 'I want a surname that feels established and timeless',
          desc_zh: '希望这个姓氏一听就有稳稳的熟悉感',
          filters: [{ field: 'era', op: 'any_of', value: ['ancient', 'traditional'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Let the best rhythm win',
          label_zh: '让最好听的节奏自己出现',
          desc_en: 'Keep the result broad and compare several flows',
          desc_zh: '先保留范围，比较不同全名的节奏差异',
          filters: [],
        },
      ],
    },
  ],
  'cute-girl': [
    {
      round: 1,
      question_en: 'What kind of cute are you after?',
      question_zh: '你想要哪一种“可爱感”？',
      options: [
        {
          emoji: '🎀',
          label_en: 'Sweet and classic',
          label_zh: '甜甜的经典可爱',
          desc_en: 'Soft, lovable names that feel instantly charming',
          desc_zh: '柔软讨喜，一听就很招人喜欢',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cute', 'gentle', 'warm'] }],
        },
        {
          emoji: '🫧',
          label_en: 'Light and playful',
          label_zh: '轻盈俏皮',
          desc_en: 'Names with bounce, sparkle, and little mischief',
          desc_zh: '轻快活泼，像气泡一样有灵气',
          filters: [{ field: 'vibe', op: 'any_of', value: ['playful', 'cute', 'bright'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Cute with a dreamy twist',
          label_zh: '梦幻系可爱',
          desc_en: 'Still adorable, but with moonlight, stars, or fantasy softness',
          desc_zh: '还是可爱，但会多一点月光和梦幻感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cute', 'mysterious', 'serene'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the scene that best matches your cute-name mood',
      question_zh: '选一个最像你理想可爱名字氛围的场景',
      options: [
        {
          emoji: '🌸',
          label_en: 'Cherry blossoms and pastel light',
          label_zh: '樱花与浅色光线',
          desc_en: 'Petal-soft, pretty, and openly sweet',
          desc_zh: '花瓣一样轻软，甜甜的也很好看',
          filters: [{ field: 'element', op: 'any_of', value: ['flower', 'light', 'wind'] }],
        },
        {
          emoji: '⭐',
          label_en: 'Stars and glitter after dark',
          label_zh: '夜色里发亮的星星与闪光',
          desc_en: 'Cute, lively, and a little magical',
          desc_zh: '可爱活泼，也带一点亮晶晶的梦感',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'light', 'moon'] }],
        },
        {
          emoji: '🍓',
          label_en: 'A picnic full of color and laughter',
          label_zh: '充满颜色和笑声的野餐',
          desc_en: 'Playful, warm, and easy to smile at',
          desc_zh: '俏皮温暖，让人很容易联想到笑意',
          filters: [{ field: 'element', op: 'any_of', value: ['sun', 'flower', 'earth'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'When someone says the name, how should it sound?',
      question_zh: '当别人念出这个名字时，你希望它听起来怎样？',
      options: [
        {
          emoji: '🍬',
          label_en: 'Sweet and easy to remember',
          label_zh: '甜甜的、很好记',
          desc_en: 'Simple charm with an instantly likable sound',
          desc_zh: '简单讨喜，听一次就容易记住',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🪷',
          label_en: 'Gentle and timeless',
          label_zh: '温柔耐看',
          desc_en: 'Cute, but with enough grace to stay elegant over time',
          desc_zh: '可爱里带一点耐看的优雅，不会太轻飘',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'modern'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Any version of cute works',
          label_zh: '哪种可爱都可以',
          desc_en: 'Keep it broad and let the best full name surface',
          desc_zh: '先保留更多结果，让最合适的全名自己出现',
          filters: [],
        },
      ],
    },
  ],
  all: [
    {
      round: 1,
      question_en: 'Where do you want to start your Japanese name search?',
      question_zh: '你想从哪种方向开始找日本名字？',
      options: [
        {
          emoji: '🌸',
          label_en: 'Soft, pretty, and expressive',
          label_zh: '柔美、好看、有表达感',
          desc_en: 'Great for feminine or poetic full-name ideas',
          desc_zh: '适合偏女性向、唯美向、角色感强的名字',
          filters: [{ field: 'gender', op: 'any_of', value: ['female', 'unisex'] }],
        },
        {
          emoji: '⚔️',
          label_en: 'Strong, calm, and dependable',
          label_zh: '稳重、有力、可靠',
          desc_en: 'Great for masculine or grounded name ideas',
          desc_zh: '适合偏男性向或更沉稳的名字路线',
          filters: [{ field: 'gender', op: 'any_of', value: ['male', 'unisex'] }],
        },
        {
          emoji: '🏷️',
          label_en: 'Start from surnames first',
          label_zh: '先从姓氏开始看',
          desc_en: 'Browse family names before pairing given names',
          desc_zh: '先挑姓，再慢慢配名字',
          filters: [{ field: 'name_part', op: 'eq', value: 'family_name' }],
        },
        {
          emoji: '🎲',
          label_en: 'Show me everything',
          label_zh: '都给我看看',
          desc_en: 'Keep the collection broad and exploratory',
          desc_zh: '先大范围逛一遍，再缩小范围',
          filters: [],
        },
      ],
    },
    {
      round: 2,
      question_en: 'What matters most in the perfect name?',
      question_zh: '一个理想名字里，你最看重什么？',
      options: [
        {
          emoji: '💮',
          label_en: 'Beautiful meaning',
          label_zh: '含义要美',
          desc_en: 'I care most about the symbolism behind the kanji',
          desc_zh: '我最看重汉字背后的寓意',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'gentle', 'noble'] }],
        },
        {
          emoji: '🎼',
          label_en: 'Good rhythm out loud',
          label_zh: '念起来要顺',
          desc_en: 'I want names that sound balanced and natural',
          desc_zh: '我更在意读音节奏和整体顺口度',
          filters: [{ field: 'syllable_count', op: 'any_of', value: ['2', '3'] }],
        },
        {
          emoji: '🕰️',
          label_en: 'A specific era or style',
          label_zh: '要有明确时代风格',
          desc_en: 'I want the name to feel classic or modern on purpose',
          desc_zh: '希望名字带出明显的时代感',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'modern', 'trending'] }],
        },
      ],
    },
  ],
  cool: [
    {
      round: 1,
      question_en: 'What kind of cool should the name give off first?',
      question_zh: '你想让这个名字先散发哪一种“酷”？',
      options: [
        {
          emoji: '🗡️',
          label_en: 'Sharp and striking',
          label_zh: '利落锋利',
          desc_en: 'Clean lines, strong presence, and immediate edge',
          desc_zh: '线条感强，一出现就很有锋芒',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cool', 'edgy', 'strong'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Quiet and mysterious',
          label_zh: '安静神秘',
          desc_en: 'Cool in a restrained, almost cinematic way',
          desc_zh: '不是张扬的酷，而是很有画面感的冷调',
          filters: [{ field: 'vibe', op: 'any_of', value: ['mysterious', 'cool', 'serene'] }],
        },
        {
          emoji: '⚡',
          label_en: 'Modern and high-energy',
          label_zh: '现代有动能',
          desc_en: 'A cooler style with momentum, confidence, and drive',
          desc_zh: '更现代、更有行动力，也更容易带出角色张力',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cool', 'edgy', 'bright'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Show me the full spectrum of cool',
          label_zh: '给我看看不同层次的酷',
          desc_en: 'Keep the page broad and compare multiple cool-name routes',
          desc_zh: '先保留更宽的范围，比较不同“酷名”路线',
          filters: [],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the image that best matches your cool-name mood',
      question_zh: '选一个最像你理想“酷名字”气氛的画面',
      options: [
        {
          emoji: '🌌',
          label_en: 'Stars over a dark horizon',
          label_zh: '暗色地平线上的星空',
          desc_en: 'Wide, distant, and effortlessly cinematic',
          desc_zh: '有距离感，也有电影镜头一样的张力',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'dark', 'sky'] }],
        },
        {
          emoji: '🌊',
          label_en: 'Cold waves under moonlight',
          label_zh: '月光下偏冷的海浪',
          desc_en: 'Fluid, calm, and cool without trying too hard',
          desc_zh: '流动感很强，冷静又不费力',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'moon', 'wind'] }],
        },
        {
          emoji: '⛰️',
          label_en: 'A ridge line in mountain air',
          label_zh: '山风中的锋利山脊线',
          desc_en: 'Grounded, crisp, and naturally imposing',
          desc_zh: '扎实清冽，不需要夸张也很有压迫感',
          filters: [{ field: 'element', op: 'any_of', value: ['mountain', 'earth', 'wind'] }],
        },
        {
          emoji: '🔥',
          label_en: 'A spark flashing in the dark',
          label_zh: '黑暗里突然亮起的一点火光',
          desc_en: 'Fast, intense, and impossible to ignore',
          desc_zh: '速度感强，带着很直接的存在感',
          filters: [{ field: 'element', op: 'any_of', value: ['fire', 'thunder', 'light'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'When someone says the name aloud, how should it land?',
      question_zh: '当别人把这个名字念出来时，你希望它落下什么感觉？',
      options: [
        {
          emoji: '🏮',
          label_en: 'Cool with a timeless backbone',
          label_zh: '有古典骨架的酷',
          desc_en: 'Still cool, but anchored by tradition and weight',
          desc_zh: '还是酷，但更有传统质地和分量',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎧',
          label_en: 'Sleek and contemporary',
          label_zh: '流畅当代',
          desc_en: 'A name that sounds current, lean, and memorable',
          desc_zh: '听起来很当代，也更轻更利落',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Let the strongest full-name vibe win',
          label_zh: '让最有气场的全名自己胜出',
          desc_en: 'Keep the results broad and compare several flavors of cool',
          desc_zh: '保留更宽的结果，比较不同层次的酷感',
          filters: [],
        },
      ],
    },
  ],
  'cute-boy': [
    {
      round: 1,
      question_en: 'What kind of cute boy-name energy do you want?',
      question_zh: '你想要哪种“可爱男孩名”的气质？',
      options: [
        {
          emoji: '🐣',
          label_en: 'Soft & Gentle',
          label_zh: '软萌温柔',
          desc_en: 'A cute boy name that feels kind, calm, and easy to approach',
          desc_zh: '想找温柔、亲近、没有攻击性的可爱男孩名',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'serene'] }],
        },
        {
          emoji: '☀️',
          label_en: 'Bright & Cheerful',
          label_zh: '明亮开朗',
          desc_en: 'Cute names with a sunny, lively, everyday charm',
          desc_zh: '更偏阳光、活泼、很有日常亲和力的路线',
          filters: [{ field: 'vibe', op: 'any_of', value: ['bright', 'playful', 'gentle'] }],
        },
        {
          emoji: '🧸',
          label_en: 'Playful & Mischievous',
          label_zh: '淘气机灵',
          desc_en: 'A cute boy name with bounce, movement, and a little spark',
          desc_zh: '带一点灵动感、俏皮感，听起来更有少年气',
          filters: [{ field: 'vibe', op: 'any_of', value: ['playful', 'bright', 'cool'] }],
        },
        {
          emoji: '🌿',
          label_en: 'Natural & Fresh',
          label_zh: '自然清新',
          desc_en: 'Cute, light names that still feel grounded and realistic',
          desc_zh: '清爽自然，既可爱又不显得太幼态',
          filters: [{ field: 'vibe', op: 'any_of', value: ['serene', 'gentle', 'playful'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the image that feels most like your ideal cute boy name',
      question_zh: '选一个最像你理想可爱男孩名的画面',
      options: [
        {
          emoji: '🌤️',
          label_en: 'Morning light through a school window',
          label_zh: '教室窗边的晨光',
          desc_en: 'Gentle, familiar, and quietly lovable',
          desc_zh: '顺耳、温和，也很有生活感',
          filters: [{ field: 'element', op: 'any_of', value: ['light', 'wind', 'earth'] }],
        },
        {
          emoji: '🏃',
          label_en: 'A kid running across an open field',
          label_zh: '在空地上奔跑的少年',
          desc_en: 'Lively, bouncy, and full of cheerful motion',
          desc_zh: '轻快、有精神，也更偏开朗可爱',
          filters: [{ field: 'element', op: 'any_of', value: ['wind', 'earth', 'light'] }],
        },
        {
          emoji: '🌊',
          label_en: 'A clear stream with cool shade nearby',
          label_zh: '有树荫的清澈小溪',
          desc_en: 'Fresh, soft, and naturally charming',
          desc_zh: '清爽、柔和、可爱但不黏腻',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'tree', 'wind'] }],
        },
        {
          emoji: '⭐',
          label_en: 'A small spark that makes people smile',
          label_zh: '让人会心一笑的小闪光',
          desc_en: 'Cute first, but still memorable and full of personality',
          desc_zh: '先可爱，再带一点记忆点和灵气',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'light', 'fire'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How should that cuteness come across?',
      question_zh: '你希望这份“可爱”更偏哪一类？',
      options: [
        {
          emoji: '🍡',
          label_en: 'Sweet and classic',
          label_zh: '甜感经典派',
          desc_en: 'Cute in a soft, familiar, long-lasting way',
          desc_zh: '可爱但耐看，属于很稳的顺耳路线',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎧',
          label_en: 'Modern and youthful',
          label_zh: '当代少年感',
          desc_en: 'Cute with a fresh, current, more modern sound',
          desc_zh: '更有现在感，更像当代会出现的可爱男孩名',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🤝',
          label_en: 'Natural and broadly usable',
          label_zh: '自然耐用型',
          desc_en: 'Keep the name cute, but still realistic for everyday use',
          desc_zh: '有可爱感，但依然适合现实长期使用',
          filters: [{ field: 'popularity', op: 'any_of', value: ['common', 'very_common', 'uncommon'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Let different cute styles compete',
          label_zh: '先放宽，让不同可爱路线竞争',
          desc_en: 'Keep the pool broad and compare multiple flavors of cute',
          desc_zh: '先别收得太窄，让温柔、活泼、清新一起比',
          filters: [],
        },
      ],
    },
  ],
  'common-girl': [
    {
      round: 1,
      question_en: 'What kind of familiar girl-name energy do you want?',
      question_zh: '你想要哪种“常见但耐看”的女孩名气质？',
      options: [
        {
          emoji: '🌷',
          label_en: 'Soft & Gentle',
          label_zh: '温柔柔和',
          desc_en: 'A common girl name that feels kind, calm, and easy to love',
          desc_zh: '想找温柔、亲切、让人很容易产生好感的常见女孩名',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'serene'] }],
        },
        {
          emoji: '✨',
          label_en: 'Bright & Cheerful',
          label_zh: '明亮开朗',
          desc_en: 'Friendly names with a sunny, everyday charm',
          desc_zh: '带着阳光感、日常感、很好接近的路线',
          filters: [{ field: 'vibe', op: 'any_of', value: ['bright', 'playful', 'gentle'] }],
        },
        {
          emoji: '🎀',
          label_en: 'Cute but Natural',
          label_zh: '可爱但不幼态',
          desc_en: 'Sweet names that still feel realistic and broadly usable',
          desc_zh: '有点可爱，但整体还是自然、真实、常用',
          filters: [{ field: 'vibe', op: 'any_of', value: ['cute', 'gentle', 'playful'] }],
        },
        {
          emoji: '🌙',
          label_en: 'Quiet & Elegant',
          label_zh: '安静秀气',
          desc_en: 'Common names with a more polished and graceful tone',
          desc_zh: '偏清秀、克制、顺耳的常见女孩名',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'serene', 'noble'] }],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the image that fits your ideal common girl name',
      question_zh: '选一个最像你理想常见女孩名的画面',
      options: [
        {
          emoji: '🌸',
          label_en: 'A familiar spring street lined with blossoms',
          label_zh: '开满花的熟悉春日街道',
          desc_en: 'Soft, approachable, and warmly classic',
          desc_zh: '柔和、亲切，也带一点经典感',
          filters: [{ field: 'element', op: 'any_of', value: ['flower', 'light', 'wind'] }],
        },
        {
          emoji: '☀️',
          label_en: 'Morning sunlight through a classroom window',
          label_zh: '晨光照进教室窗边',
          desc_en: 'Bright, youthful, and naturally likable',
          desc_zh: '有朝气、很日常、容易让人喜欢',
          filters: [{ field: 'element', op: 'any_of', value: ['sun', 'light', 'sky'] }],
        },
        {
          emoji: '🌿',
          label_en: 'A green path after gentle rain',
          label_zh: '细雨后安静的绿道',
          desc_en: 'Fresh, calm, and quietly pretty',
          desc_zh: '清新、安静、耐看型',
          filters: [{ field: 'element', op: 'any_of', value: ['plant', 'earth', 'water'] }],
        },
        {
          emoji: '💫',
          label_en: 'A familiar place with one subtle spark',
          label_zh: '熟悉日常里的一点闪光',
          desc_en: 'Mainstream at heart, but still memorable',
          desc_zh: '整体常用，但仍想保留一点记忆点',
          filters: [{ field: 'element', op: 'any_of', value: ['light', 'star', 'moon'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How mainstream should the name feel?',
      question_zh: '你希望这个名字的“常见感”落在哪一档？',
      options: [
        {
          emoji: '📜',
          label_en: 'Classic and long-trusted',
          label_zh: '经典耐用型',
          desc_en: 'A common girl name with long-standing familiarity',
          desc_zh: '更偏传统常用、一直有人在用的路线',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎐',
          label_en: 'Modern but still everyday',
          label_zh: '现代日常型',
          desc_en: 'Current-feeling names that still sound natural in real life',
          desc_zh: '偏现代，但又不是特别跳脱的日常常用名',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s'] }],
        },
        {
          emoji: '🌟',
          label_en: 'Very common and broadly loved',
          label_zh: '高接受度主流型',
          desc_en: 'Mainstream names with immediate familiarity',
          desc_zh: '就是想找一听就很主流、很好接受的名字',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Mix it for me',
          label_zh: '都可以，帮我混着看',
          desc_en: 'Let the strongest common girl names surface naturally',
          desc_zh: '不用太限定，先把最顺眼的常见女孩名推给我',
          filters: [],
        },
      ],
    },
  ],
  'popular-girl': [
    {
      round: 1,
      question_en: 'What should a popular girl name feel like to you?',
      question_zh: '你希望“热门女孩名”首先给人什么感觉？',
      options: [
        {
          emoji: '🌷',
          label_en: 'Soft and naturally lovable',
          label_zh: '温柔亲切型',
          desc_en: 'A popular girl name that feels kind, smooth, and easy to love',
          desc_zh: '想找温柔、顺耳、接受度高的热门女孩名',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'cute'] }],
        },
        {
          emoji: '👑',
          label_en: 'Elegant and polished',
          label_zh: '优雅体面型',
          desc_en: 'Popular, but still refined and graceful',
          desc_zh: '虽然热门，但还是想保留精致、秀气和完成度',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'noble', 'serene'] }],
        },
        {
          emoji: '✨',
          label_en: 'Bright and lively',
          label_zh: '明亮有元气型',
          desc_en: 'A popular girl name with cheerful, memorable energy',
          desc_zh: '希望名字更有朝气、更亮一点，也更容易记住',
          filters: [{ field: 'vibe', op: 'any_of', value: ['bright', 'playful', 'gentle'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Show me the strongest favorites',
          label_zh: '直接看最受欢迎那批',
          desc_en: 'Keep it broad and let the best-known girl names surface',
          desc_zh: '先别收太窄，让最有代表性的热门女孩名先跑出来',
          filters: [],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the scene that matches your ideal popular girl name',
      question_zh: '选一个最像你理想热门女孩名的画面',
      options: [
        {
          emoji: '🌸',
          label_en: 'A bright spring street everyone remembers',
          label_zh: '大家都记得的春日街道',
          desc_en: 'Familiar, sweet, and full of easy charm',
          desc_zh: '熟悉、好感度高，也有一点甜和亲切感',
          filters: [{ field: 'element', op: 'any_of', value: ['flower', 'light', 'wind'] }],
        },
        {
          emoji: '☀️',
          label_en: 'Morning light through an open window',
          label_zh: '晨光照进敞亮窗边',
          desc_en: 'Clean, bright, and naturally popular',
          desc_zh: '清爽明亮，一听就很主流也很舒服',
          filters: [{ field: 'element', op: 'any_of', value: ['sun', 'light', 'sky'] }],
        },
        {
          emoji: '🌿',
          label_en: 'A calm green path that never gets old',
          label_zh: '怎么看都耐看的安静绿道',
          desc_en: 'Balanced, soft, and easy to live with for years',
          desc_zh: '平衡、柔和，也很适合长期使用',
          filters: [{ field: 'element', op: 'any_of', value: ['plant', 'earth', 'water'] }],
        },
        {
          emoji: '💫',
          label_en: 'A familiar favorite with one little spark',
          label_zh: '熟悉热门里的一点闪光',
          desc_en: 'Popular first, but with a hint of extra charm',
          desc_zh: '整体是热门路线，但还是想留一点灵气和记忆点',
          filters: [{ field: 'element', op: 'any_of', value: ['light', 'star', 'moon'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'How should the popularity feel?',
      question_zh: '你希望这个“热门感”更偏哪一种？',
      options: [
        {
          emoji: '📜',
          label_en: 'Classic and trusted',
          label_zh: '经典热门型',
          desc_en: 'A long-loved girl name with proven familiarity',
          desc_zh: '更偏传统经典、很多年代都有人喜欢的热门女孩名',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎐',
          label_en: 'Modern and everyday',
          label_zh: '现代日常型',
          desc_en: 'Current-feeling names that still sound natural',
          desc_zh: '更偏现代，但又不会太跳脱的热门女孩名',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s'] }],
        },
        {
          emoji: '🥇',
          label_en: 'Top-tier mainstream',
          label_zh: '越主流越好',
          desc_en: 'Prioritize the most familiar, most widely loved options',
          desc_zh: '优先看最主流、最熟悉、接受度最高的那批名字',
          filters: [{ field: 'popularity', op: 'any_of', value: ['very_common'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Mix classic and modern favorites',
          label_zh: '经典和现代热门都可以',
          desc_en: 'Keep both timeless and current favorites in play',
          desc_zh: '先别收得太死，让经典热门和现代热门一起竞争',
          filters: [],
        },
      ],
    },
  ],
  popular: [
    {
      round: 1,
      question_en: 'What should make a popular name feel right for you?',
      question_zh: '你希望“热门名字”最打动你的点是什么？',
      options: [
        {
          emoji: '🌸',
          label_en: 'Soft, friendly, and easy to love',
          label_zh: '温柔亲切，一听就讨喜',
          desc_en: 'I want a popular name that feels warm and naturally likable',
          desc_zh: '我想要那种大众接受度高、听起来很有亲和力的名字',
          filters: [{ field: 'vibe', op: 'any_of', value: ['gentle', 'warm', 'cute'] }],
        },
        {
          emoji: '👑',
          label_en: 'Elegant and polished',
          label_zh: '优雅体面，很有完成度',
          desc_en: 'Popular, but still refined and tasteful',
          desc_zh: '虽然常见，但依然想保留精致感和品味',
          filters: [{ field: 'vibe', op: 'any_of', value: ['elegant', 'noble', 'serene'] }],
        },
        {
          emoji: '⚡',
          label_en: 'Confident and memorable',
          label_zh: '有精神，也更容易记住',
          desc_en: 'A mainstream name with energy and presence',
          desc_zh: '希望它流行，但不能太没存在感',
          filters: [{ field: 'vibe', op: 'any_of', value: ['strong', 'cool', 'bright'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Just show me the best-known favorites',
          label_zh: '直接给我看最受欢迎的那批',
          desc_en: 'Keep the pool broad and let the strongest common names rise',
          desc_zh: '先不缩太窄，让高人气名字自己跑出来',
          filters: [],
        },
      ],
    },
    {
      round: 2,
      question_en: 'Pick the scene that matches your ideal popular-name vibe',
      question_zh: '选一个最像你理想“热门名字”气氛的场景',
      options: [
        {
          emoji: '🌤️',
          label_en: 'Morning light in a lively neighborhood',
          label_zh: '热闹街区里透进来的晨光',
          desc_en: 'Bright, approachable, and full of everyday charm',
          desc_zh: '明亮、自然，也有一种日常里的好感度',
          filters: [{ field: 'element', op: 'any_of', value: ['light', 'sun', 'sky'] }],
        },
        {
          emoji: '🌊',
          label_en: 'A calm riverside everyone loves to visit',
          label_zh: '大家都喜欢去的安静河岸',
          desc_en: 'Familiar, flowing, and quietly timeless',
          desc_zh: '大众熟悉、流动自然，也不会太快过时',
          filters: [{ field: 'element', op: 'any_of', value: ['water', 'wind', 'moon'] }],
        },
        {
          emoji: '🌿',
          label_en: 'A green path that feels instantly comfortable',
          label_zh: '走上去就让人放松的绿意小路',
          desc_en: 'Soft, balanced, and easy to live with',
          desc_zh: '舒服、平衡，也很适合长期使用',
          filters: [{ field: 'element', op: 'any_of', value: ['earth', 'flower', 'mountain'] }],
        },
        {
          emoji: '✨',
          label_en: 'A familiar name with a little sparkle',
          label_zh: '熟悉里带一点闪光感',
          desc_en: 'Popular first, but still a little special',
          desc_zh: '整体是热门路线，但还是想留一点灵气',
          filters: [{ field: 'element', op: 'any_of', value: ['star', 'light', 'flower'] }],
        },
      ],
    },
    {
      round: 3,
      question_en: 'When people hear the name, what kind of popularity should it suggest?',
      question_zh: '当别人听到这个名字时，你希望它呈现怎样的“热门感”？',
      options: [
        {
          emoji: '🏯',
          label_en: 'A long-loved classic',
          label_zh: '经久不衰的经典热门',
          desc_en: 'A name people have trusted across generations',
          desc_zh: '那种跨时代都有人在用、很稳的热门名字',
          filters: [{ field: 'era', op: 'any_of', value: ['traditional', 'ancient'] }],
        },
        {
          emoji: '🎧',
          label_en: 'Current and modern',
          label_zh: '当代流行、很有现在感',
          desc_en: 'A popular name that sounds fresh right now',
          desc_zh: '更偏今天会流行的发音和气质',
          filters: [{ field: 'era', op: 'any_of', value: ['modern', '2000s', 'trending'] }],
        },
        {
          emoji: '🥇',
          label_en: 'As mainstream as possible',
          label_zh: '越主流越好',
          desc_en: 'Prioritize the most familiar, top-tier common names',
          desc_zh: '优先看最主流、最常见、接受度最高的一批',
          filters: [{ field: 'popularity', op: 'any_of', value: ['very_common'] }],
        },
        {
          emoji: '🎲',
          label_en: 'Mix classic favorites and modern staples',
          label_zh: '经典热门和现代常用都可以',
          desc_en: 'Keep both kinds of popular names in play',
          desc_zh: '别收得太窄，让不同年代的热门名一起竞争',
          filters: [],
        },
      ],
    },
  ],
}
